Goals:
1. Convert all NaN data into median values of each of those column
2. Delete all duplicate rows

In [1]:
# import library
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset

# loading data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# data cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [ ]:
df.loc[:10, 'salary_year_avg':'salary_hour_avg']

# Nilai yang Nan, mau di convert jadi nilai median

    salary_year_avg  salary_hour_avg
0               NaN              NaN
1               NaN              NaN
2               NaN              NaN
3               NaN              NaN
4               NaN              NaN
5               NaN              NaN
6               NaN              NaN
7               NaN              NaN
8               NaN              NaN
9               NaN              NaN
10              NaN              NaN

In [12]:
salary_yearly_median = df.salary_year_avg.median()

In [9]:
salary_hourly_median = df.salary_hour_avg.median()

In [18]:
# create dataframe baru, agar yang original tetap intact
df_filled = df

# reassign yang nan value dengan median value
df_filled['salary_year_avg'] = df_filled.salary_year_avg.fillna(salary_yearly_median)
df_filled['salary_hour_avg'] = df_filled.salary_hour_avg.fillna(salary_hourly_median)

In [20]:
df_filled.loc[:10, 'salary_year_avg':'salary_hour_avg']

    salary_year_avg  salary_hour_avg
0          115000.0            45.98
1          115000.0            45.98
2          115000.0            45.98
3          115000.0            45.98
4          115000.0            45.98
5          115000.0            45.98
6          115000.0            45.98
7          115000.0            45.98
8          115000.0            45.98
9          115000.0            45.98
10         115000.0            45.98

In [ ]:
# delete duplicate 
df_unique = df_filled

df_unique = df_unique.drop_duplicates()
print('Length of Original data  :     ', len(df_filled))
print('Length of droped data    :     ', len(df_unique))
print('Droped data              :     ', len(df_filled)-len(df_unique))

Length of Original data  :      785741
Length of droped data    :      785640
Droped data              :      101

In [ ]:
# delete duplicate spesific (job title and company name)
df_unique = df_filled

df_unique = df_unique.drop_duplicates(subset=['job_title','company_name'])
print('Length of Original data  :     ', len(df_filled))
print('Length of droped data    :     ', len(df_unique))
print('Droped data              :     ', len(df_filled)-len(df_unique))

Length of Original data  :      785741
Length of droped data    :      508042
Droped data              :      277699